config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :comments, except: [:index, :new]
  resources :ideas
  resources :likes #, only: [:create, :destroy]

	

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include Likeable

	belongs_to :idea
	belongs_to :user
 	# has_many :likes, as: :objects

	validates :idea_id, :user_id, presence: true
	validates :body, length: {maximum: 30}, presence: true

	before_save :sanitize_body

	private
	def sanitize_body
		self.body.rstrip!
	end

end

app/models/concerns/likeable.rb
module Likeable
  extend ActiveSupport::Concern

  included do
    has_many :likes, as: :obj
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	
  include Likeable

  mount_uploader :picture, PictureUploader

	has_many :comments
  belongs_to :user

  scope :with_picture, -> { where.not(picture: :null) }
  scope :without_picture, -> { where(picture: :null) } 

  scope :with_description, -> { where.not(description: :null) }
  scope :without_description, -> { where(description: :null) }

  validates :name, length: {minimum: 5}
  validates :user_id , presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :obj, polymorphic: true

  validates :user_id, :obj_type, :obj_id, presence: true
  validates_uniqueness_of :user_id, scope: [:obj_type, :obj_id]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :ideas
   has_many :comments
   has_many :likes
   
   validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, message:"Email should contain @"}
   validates :name, :last_name, format: {with: /\A[a-z,A-Z]+\z/,message:"Only letters are valid"}
   
   def full_name
   		self.name + " " + self.last_name
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments/1
  # GET /comments/1.json
  def show
  end


  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @last_comment = Idea.find(params[:idea_id]).comments.last
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.js 
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id, :user_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_comment, only: [:index, :show]

  # GET /ideas
  # GET /ideas.json
  def index
    if params[:description].present?
      @ideas = Idea.where(['description LIKE ? or name LIKE ?', "%#{params[:description]}%", "%#{params[:description]}%"])
    else
      @ideas = Idea.all
    end
    
    respond_to do |format|
      format.html
      format.js
    end

  end

  def new
    @idea = Idea.new
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def set_comment
      @comment = Comment.new(idea: @idea)      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_object, only: [:create]
  before_action :set_comment

  def create  
    @like = Like.create!(user: current_user, obj_id: params[:obj_id], obj_type: params[:obj_type].titleize)
    choose_object
    respond_to do |format|
      if @object.increment!(:likes_count,1) 
        set_render format
      else
        format.html { render :index}
      end
    end
  end

  def destroy
    @like = Like.where(id:params[:id], user_id:current_user.id).first
    choose_object

    respond_to do |format|
      if @like.obj_type.classify.constantize.find(@like.obj_id).decrement!(:likes_count, 1)
        @like.destroy
        set_render format
      end
    end
  end

  private
    def set_render format
        if @like.obj_type == "Idea"
          format.js{ render file: "likes/idea.js.haml"}
        elsif @like.obj_type == "Comment"
          format.js{ render  :file => "likes/comment.js.haml" }
        end
    end

    def choose_object
      if @like.obj_type == "Idea"
        @idea = Idea.find(@like.obj_id)
      else
        @comment = Comment.find(@like.obj_id)
      end
    end

    def set_comment
      @comment = Comment.new
    end

    def set_object
      @object = params[:obj_type].classify.constantize.find(params[:obj_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/_comment.html.haml
.full-name
  = comment.user.full_name
%span.body
  = comment.body
%br
= "#{comment.created_at.strftime('%d %b. %Y')} às #{comment.created_at.strftime('%H:%M')} "
-if comment.likes.where(user_id: current_user.id).count == 0
  =render partial: "comments/like", object: comment, as: 'comment'
-else
  =render partial: "comments/unlike", object: comment, as: 'comment'
%p
  .likes-comment
    -if comment.likes_count == 0
      %span{:id => "Comment_#{comment.id}"}
      = " "
    -else
      %span{:id => "Comment_#{comment.id}"}
        = t('ideas.idea.comment.likes_count', count: comment.likes_count) 

/ %hr.line/

app/views/comments/_form.html.haml
= form_for @comment, html: { class: "form form-horizontal comment" } do |f|
  .form-group
    = f.label :body, class: 'control-label'
    .controls
      = f.text_field :body, class: 'form-control', required: true
    = error_span(@comment[:body])
  .form-group
    = f.label :idea_id, class: 'control-label'
    .controls
      = f.text_field :idea_id, class: 'form-control', required: true
    = error_span(@comment[:idea_id])
  .form-group
    = f.label :user_id, class: 'control-label'
    .controls
      = f.text_field :user_id, class: 'form-control', required: true
    = error_span(@comment[:user_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), comments_path, :class => 'btn btn-default'

app/views/comments/_like.html.haml
= link_to 'Like', likes_path(obj_type: :comment, obj_id: comment.id), method: :post, class: "a-like like-comment", id: comment.id, remote: true

app/views/comments/_unlike.html.haml
-comment.likes.each do |like|
  -if like.user_id == current_user.id
    = link_to "Unlike", "likes/#{like.id}", method: :delete, class: "a-like like-comment", id: comment.id, remote: true

app/views/comments/create.js.haml
var $html = "#{escape_javascript( render :partial => 'comment', :locals => {:comment => @comment })}"
$("div#Idea_#{@comment.idea_id}").append($html);

$("#field-comment-#{@comment.idea_id}").val("");

app/views/comments/edit.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/comments/index.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:idea_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to comment.id, comment_path(comment)
        %td= comment.body
        %td= comment.idea_id
        %td= comment.user_id
        %td=l comment.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(comment), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(comment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_comment_path, :class => 'btn btn-primary'

app/views/comments/new.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/comments/show.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @comment.body
%p
  %strong= model_class.human_attribute_name(:idea_id) + ':'
  %br
  = @comment.idea_id
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @comment.user_id


= link_to t('.back', :default => t("helpers.links.back")), comments_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(@comment), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(@comment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/ideas/_form.html.haml
= form_for @idea, html: { class: "form form-horizontal idea" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@idea[:name])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@idea[:description])
  .form-group
    = f.label :picture, class: 'control-label'
    .controls
      = f.file_field :picture, class: 'form-control', required: true
    = error_span(@idea[:picture])

  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), ideas_path, :class => 'btn btn-default'

app/views/ideas/_idea.html.haml
.idea{:id => "Idea_#{idea.id}"}
  %p.full-name
    = idea.user.full_name
  %p.created-at
    = " #{idea.created_at.strftime('%d %b. %Y')} às #{idea.created_at.strftime('%H:%M')} "
  %p.description
    = idea.description
  .picture
    = image_tag idea.picture_url(:thumb) if idea.picture?
  .like{:id => "Like_Idea_#{idea.id}"}
    -if idea.likes.where(user_id: current_user.id).count == 0
      =render partial: "ideas/like", object: idea, as: 'idea'
    -else
      =render partial: "ideas/unlike", object: idea, as: 'idea'
  %hr.line/
  %p
    .likes-idea
      -if idea.likes_count == 0
        %span{:id => "Idea_#{idea.id}"}
        = " "
      -else
        %span{:id => "Idea_#{idea.id}"}
          = t('.likes_count', count: idea.likes_count) 
  %hr.line/
  - idea.comments.each do |comment|
    .comment{:id => "Comment_#{comment.id}"}
      =render partial: comment
    %hr.line/

= form_for(@comment, remote: true) do |f|
  .form-group
    .controls
      = f.text_field :body, class: 'form-control', placeholder: "Write a comment", id: "field-comment-#{idea.id}"
    .controls
      = f.hidden_field :idea_id, class: 'form-control', value: idea.id
    .controls
      = f.hidden_field :user_id, class: 'form-control', value: current_user.id
    %br
    .actions
      = f.submit nil, class: 'btn btn-primary'

app/views/ideas/_ideas.html.haml
- ideas.each do |idea|
  .content
    =render partial: "idea", object: idea, as: 'idea'

app/views/ideas/_like.html.haml
= link_to 'Like', likes_path(obj_type: :idea, obj_id: idea.id), method: :post, class: "a-like like-idea", id: idea.id, remote: true

app/views/ideas/_unlike.html.haml
-idea.likes.each do |like|
  -if like.user_id == current_user.id
    = link_to "Unlike", "likes/#{like.id}", method: :delete, class: "a-like like-idea", id: idea.id, remote: true

app/views/ideas/edit.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/ideas/index.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

  = form_tag :ideas, method: :get, remote: true do
    = field_set_tag do
      .controls
      = text_field_tag :description
      .actions
      = submit_tag "BUSCAR", class: "btn btn-default"
%br

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:picture)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @ideas.each do |idea|
      %tr
        %td= link_to idea.id, idea_path(idea)
        %td= idea.name
        %td= idea.description
        %td= idea.picture
        %td= idea.user_id
        %td=l idea.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_idea_path(idea), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), idea_path(idea), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_idea_path, :class => 'btn btn-primary'

.ideas
  =render partial: "ideas", object: @ideas, as: 'ideas'

app/views/ideas/index.js.haml
var $html = "#{escape_javascript( render :partial => 'ideas', object: @ideas, as: 'ideas')}"

$(".ideas").empty();
$(".ideas").append($html);

app/views/ideas/new.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/ideas/search.html.haml
- @ideas.each do |idea|
  .content
    =render partial: "idea", object: idea, as: 'idea'

app/views/ideas/show.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

=render partial: "idea", locals: {idea: @idea}

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Railsapp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Railsapp
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
      %footer
        %p &copy; Company 2015

app/views/likes/_form.html.haml
= form_for @like do |f|
  - if @like.errors.any?
    #error_explanation
      %h2= "#{pluralize(@like.errors.count, "error")} prohibited this like from being saved:"
      %ul
        - @like.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :obj_type
    = f.text_field :obj_type
  .field
    = f.label :obj_id
    = f.number_field :obj_id
  .actions
    = f.submit 'Save'

app/views/likes/comment.js.haml
var $html = "#{ escape_javascript( render partial:'comments/comment', :locals => { comment: @comment } )}"; |
$("div#Comment_#{@like.obj_id}").html($html); 

app/views/likes/edit.html.haml
%h1 Editing like

= render 'form'

= link_to 'Show', @like
\|
= link_to 'Back', likes_path

app/views/likes/idea.js.haml
var $html = "#{ escape_javascript( render partial:'ideas/idea', :locals => { idea: @idea, comment: @comment } ) }"; |
$("div#Idea_#{@idea.id}").parent().html($html);

app/views/likes/index.html.haml
%h1 Listing likes

%table
  %thead
    %tr
      %th User
      %th Object type
      %th Object
      %th
      %th
      %th
      
  %tbody
    - @likes.each do |like|
      %tr
        %td= like.user_id
        %td= like.obj_type
        %td= like.obj_id
        %td= link_to 'Show', like
        %td= link_to 'Edit', edit_like_path(like)
        %td= link_to 'Destroy', like, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Like', new_like_path

app/views/likes/new.html.haml
%h1 New like

= render 'form'

= link_to 'Back', likes_path

app/views/likes/show.html.haml
%p#notice= notice

%p
  %b User:
  = @like.user_id
%p
  %b Object type:
  = @like.obj_type
%p
  %b Object:
  = @like.obj_id

= link_to 'Edit', edit_like_path(@like)
\|
= link_to 'Back', likes_path